export interface Country {
	id: string;
	label: string;
}

export const countries: Country[] = [
	{ id: 'US', label: 'United States Of America' },
	{ id: 'AD', label: 'Andorra' },
	{ id: 'AI', label: 'Anguilla' },
	{ id: 'AR', label: 'Argentina' },
	{ id: 'AU', label: 'Australia' },
	{ id: 'AT', label: 'Austria' },
	{ id: 'AZ', label: 'Azerbaijan' },
	{ id: 'BS', label: 'Bahamas' },
	{ id: 'BH', label: 'Bahrain' },
	{ id: 'BB', label: 'Barbados' },
	{ id: 'BE', label: 'Belgium' },
	{ id: 'BM', label: 'Bermuda' },
	{ id: 'BR', label: 'Brazil' },
	{ id: 'BG', label: 'Bulgaria' },
	{ id: 'CA', label: 'Canada' },
	{ id: 'CL', label: 'Chile' },
	{ id: 'CN', label: 'China' },
	{ id: 'CO', label: 'Colombia' },
	{ id: 'CR', label: 'Costa Rica' },
	{ id: 'HR', label: 'Croatia' },
	{ id: 'CY', label: 'Cyprus' },
	{ id: 'CZ', label: 'Czech Republic' },
	{ id: 'DK', label: 'Denmark' },
	{ id: 'DO', label: 'Dominican Republic' },
	{ id: 'EC', label: 'Ecuador' },
	{ id: 'EE', label: 'Estonia' },
	{ id: 'FO', label: 'Faroe Islands' },
	{ id: 'FI', label: 'Finland' },
	{ id: 'FR', label: 'France' },
	{ id: 'GE', label: 'Georgia' },
	{ id: 'DE', label: 'Germany' },
	{ id: 'GH', label: 'Ghana' },
	{ id: 'GI', label: 'Gibraltar' },
	{ id: 'GB', label: 'Great Britain' },
	{ id: 'GR', label: 'Greece' },
	{ id: 'HK', label: 'Hong Kong' },
	{ id: 'HU', label: 'Hungary' },
	{ id: 'IS', label: 'Iceland' },
	{ id: 'IN', label: 'India' },
	{ id: 'IE', label: 'Ireland' },
	{ id: 'IL', label: 'Israel' },
	{ id: 'IT', label: 'Italy' },
	{ id: 'JM', label: 'Jamaica' },
	{ id: 'JP', label: 'Japan' },
	{ id: 'KR', label: 'Korea, Republic of' },
	{ id: 'LV', label: 'Latvia' },
	{ id: 'LB', label: 'Lebanon' },
	{ id: 'LT', label: 'Lithuania' },
	{ id: 'LU', label: 'Luxembourg' },
	{ id: 'MY', label: 'Malaysia' },
	{ id: 'MT', label: 'Malta' },
	{ id: 'MX', label: 'Mexico' },
	{ id: 'MC', label: 'Monaco' },
	{ id: 'ME', label: 'Montenegro' },
	{ id: 'MA', label: 'Morocco' },
	{ id: 'NL', label: 'Netherlands' },
	{ id: 'AN', label: 'Netherlands Antilles' },
	{ id: 'NZ', label: 'New Zealand' },
	{ id: 'ND', label: 'Northern Ireland' },
	{ id: 'NO', label: 'Norway' },
	{ id: 'PE', label: 'Peru' },
	{ id: 'PL', label: 'Poland' },
	{ id: 'PT', label: 'Portugal' },
	{ id: 'RO', label: 'Romania' },
	{ id: 'RU', label: 'Russian Federation' },
	{ id: 'LC', label: 'Saint Lucia' },
	{ id: 'SA', label: 'Saudi Arabia' },
	{ id: 'RS', label: 'Serbia' },
	{ id: 'SG', label: 'Singapore' },
	{ id: 'SK', label: 'Slovakia' },
	{ id: 'SI', label: 'Slovenia' },
	{ id: 'ZA', label: 'South Africa' },
	{ id: 'ES', label: 'Spain' },
	{ id: 'SE', label: 'Sweden' },
	{ id: 'CH', label: 'Switzerland' },
	{ id: 'TW', label: 'Taiwan' },
	{ id: 'TH', label: 'Thailand' },
	{ id: 'TT', label: 'Trinidad and Tobago' },
	{ id: 'TR', label: 'Turkey' },
	{ id: 'UA', label: 'Ukraine' },
	{ id: 'AE', label: 'United Arab Emirates' },
	{ id: 'UY', label: 'Uruguay' },
	{ id: 'VE', label: 'Venezuela' }
];
